import "../styles/index.css";
import { Amplify, Auth } from "aws-amplify";
import { merged } from "../contexts/authentication/initialize";
import Link from "next/link";
import GlobalHeader from "../components/GlobalHeader";
import styles from "./layout.module.css";
import ThemeSetter from "../components/ThemeSetter";
Amplify.configure(merged);

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeSetter />
      <body className={styles.body}>
        <GlobalHeader />
        {children}
      </body>
    </html>
  );
}
