import '../styles/index.css';
import { Amplify, Auth } from "aws-amplify"
import { merged } from "../contexts/authentication/initialize";

Amplify.configure(merged)

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
