import "../styles/index.css";
import { Amplify, Auth } from "aws-amplify";
import { merged } from "../contexts/authentication/initialize";
import Link from "next/link";
import GlobalHeader from "../components/GlobalHeader";
import styles from "./layout.module.css";
import ThemeSetter from "../components/ThemeSetter";
Amplify.configure(merged);

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const setTheme = function setTheme() {
  if (localStorage.theme === "dark") {
    document.documentElement.classList.add("dark");
  } else if (localStorage.theme === "light") {
    document.documentElement.classList.add("light");
  } else if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
    document.documentElement.classList.add("dark");
  } else {
    document.documentElement.classList.add("light");
  }
};

const scriptContent = {
  __html: `
    ${setTheme.toString()};
    setTheme();
  `,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={scriptContent} />
      </head>

      <body className={styles.body}>
        <GlobalHeader />
        {children}
      </body>
    </html>
  );
}
